### PR TITLE
add css to bet

### PR DESCRIPTION
**Pull request by carlendev**
Don't forget to add it on the Admin view (and maybe contributors view)

### CODE REVIEW

**Comment by ludovicgueth** [comment]
@carlendev bet styling is done, need to test it with a few users

**Comment by carlendev** [comment]
@ludovicgueth I'll do it before merging

**Comment by carlendev** [comment]
@ludovicgueth If you would like to test it yourself, just add users in the DB and create fake bets in dev DB

**Comment by ludovicgueth** [comment]
capture d ecran 2018-03-03 a 16 10 48
it's looking good @carlendev

**Comment by carlendev** [comment]
@ludovicgueth You can bet multiple time on the same project ? If it's the case it's a major bug

**Pull request merged**
